# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tech blog + Competitive coding
email: azjargalgankhuyag13@gmail.com
description: > # this means to ignore newlines until "baseurl:"

  This blog for sharing my technical notes mostly about VueJS, Typescript and similar frameworks.
  Also willing to share my understanding of competitive coding and like to explain how to approach or solve them.
  
github_username:  azaa13

# Build settings
markdown: kramdown